basePath: /
host: localhost:8000
info:
  contact: {}
  description: RESTful API.
  title: ToDo App 2021
  version: Beta
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: Header
    name: Authorization
    type: apiKey
swagger: "2.0"
